name: Test app with PostgreSQL

on:
  push:
    branches: [master]

jobs:
  run_app:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: q
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DB_HOST: postgres
      DB_NAME: q
      DB_USER: postgres
      DB_PASSWORD: secret

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: pip install psycopg2-binary
      - name: Run app
        run: python app.py
